services:
  backend:
    build: ./lex_app_backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./lex_app_backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./lex_app_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./lex_app_frontend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
